name: Cypress tests
on:
  workflow_dispatch
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@2.3.4
      - name: Cypress.io
        uses: cypress.io/github-action@2.9.7
        with:
          build: npm run build
          start: npm start
          browser: chrome
